### ISSUE TITLE
Running torchrec on torchvision models

### ISSUE THREAD

**Issue by t-vi** [ahgamut/torchrecorder#1]
Hi,

I learned about torchrec recently, thank you for making it! 
I wanted to give it a spin, so I tried it on the torchvision resnet and vgg models, but it seems to run into a key error with those.
I'm not sure whether this is due to structural things like inplace relu or reusing relu modules or something like this.

Best regards

Thomas

**Comment by ahgamut** [comment]
@t-vi Can you show me some log/debug output or screenshot of the error you have?

I haven't tested this package with newer versions of PyTorch.
