### ISSUE TITLE
TorchRecorder - nn.Sequential

### ISSUE THREAD

**Issue by karkir0003** [ahgamut/torchrecorder#2]
I have a model that is of the form

```
class SimpleModel(nn.Module):
    nn.Sequential(*[nn.Linear(10, 3), nn.Linear(3, 50), nn.ReLu(), nn.Linear(50, 1)])
```
I'm trying to use `torchrecorder.render_network()`, but I'm getting an error where the PNG is not being generated. Can someone please advise

**Comment by karkir0003** [comment]
@ahgamut

**Comment by LucasZhang58** [comment]
I am getting this error 'KeyError: tensor([[0.2135, 0.4540, 0.3325]], requires_grad=True)' whenever I ask for the input shape of x_train.size()[1:]. @ahgamut

**Comment by ahgamut** [comment]
Hi @LucasZhang58 @karkir0003, I have pushed a fix for this bug to the repo -- now it works with `nn.Sequential` as expected. Here's a working example: 

```python
import sys
import torch
import torchrecorder

nn = torch.nn

class SimpleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mod = nn.Sequential(
            *[nn.Linear(10, 3), nn.Linear(3, 50), nn.ReLU(), nn.Linear(50, 1)]
        )

    def forward(self, inputs):
        return self.mod(inputs)


def main():
    i = 3
    net = SimpleModel()
    torchrecorder.render_network(
        net,
        name="SimpleModel",
        input_shapes=(1, 10),
        directory="./",
        fmt="svg",
        render_depth=i,
    )


if __name__ == "__main__":
    main()
```

![SimpleModel-3](https://user-images.githubusercontent.com/41098605/188290329-e1de1d07-095d-4081-b27f-56a1250bc96e.svg)

**Comment by ahgamut** [comment]
You can clone the repo and confirm that it works. Let me know if there are other bugs, or you'd like a new release on PyPi.

**Comment by karkir0003** [comment]
id like a new release on PyPi please @ahgamut

**Comment by ahgamut** [comment]
@karkir0003 here you go: https://pypi.org/project/torchrecorder/1.0.3/

Enjoy!

**Comment by karkir0003** [comment]
Sorry I saw this message a bit late, but thank you for responding
